// Auto generated by utensor-cli

#ifndef __MODELS_PREDICTOR_H
#define __MODELS_PREDICTOR_H
#include "uTensor/core/context.hpp"
void get_predictor_ctx(Context& ctx, Tensor* input_0);
#endif // __MODELS_PREDICTOR_H