// Auto generated by utensor-cli

#include <stdint.h>

const int inline_MatMul_eightbit_X__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_MatMul_eightbit_X__port__0_reduction_dims_0 [ 1 ] = {  0,  };
#include <stdint.h>

const float inline_W_0 [ 3 ] = {  0.028367981,  0.683743,  0.22468291,  };
#include <stdint.h>

const int inline_MatMul_eightbit_W__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_MatMul_eightbit_W__port__0_reduction_dims_0 [ 1 ] = {  0,  };
#include <stdint.h>

const float inline_b_0 [ 1 ] = {  -13.289205,  };
#include <stdint.h>

const int inline_y_pred_eightbit_b__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_y_pred_eightbit_b__port__0_reduction_dims_0 [ 1 ] = {  0,  };
